<?php

namespace bestophe\VideoCollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository {

    public function findMedia($id) {

        $qb = $this->createQueryBuilder('m');
        $qb
                ->where('m.id= :id')
                ->setParameter('id', $id)
        ;
        return $qb
                        ->getQuery()
                        ->getOneOrNullResult()
        //  ->getResult()
        ;
    }

    public function findAllMedias() {
        $qb = $this->createQueryBuilder('m');
        $qb->orderBy('m.name', 'ASC');

        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }
    
    public function findAllMediasId() {
        $qb = $this->createQueryBuilder('m');
        $qb->select('m.id');

        return $qb
                        ->getQuery()
                        ->getScalarResult();
    }

}
