<?php

namespace bestophe\VideoCollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository {

    public function findPerson($id) {

        $qb = $this->createQueryBuilder('p');
        $qb
                ->where('p.id= :id')
                ->setParameter('id', $id)
        ;
        return $qb
                        ->getQuery()
                        ->getOneOrNullResult()
        //  ->getResult()
        ;
    }

    public function findPersonName($id) {

        $qb = $this->createQueryBuilder('p');
        $qb
                ->select(array('p.name'))
                ->where('p.id= :id')
                ->setParameter('id', $id)
        ;
        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function findAllPerson() {

        $qb = $this->createQueryBuilder('p');
        $qb
                ->select(array('p.id','p.name'))
        ;
        return $qb
                        ->getQuery()
                       // ->getArrayResult()
                        ->getScalarResult()
        ;
    }

}
